# query-engine/trino-values.yaml
# Helm configuration for Trino querying Apache Iceberg on Ozone

server:
  workers: 1

coordinator:
  jvm:
    maxHeapSize: "1536M"
  resources:
    requests:
      cpu: 200m
      memory: 1536Mi
    limits:
      cpu: 2
      memory: 2Gi

worker:
  jvm:
    maxHeapSize: "1536M"
  resources:
    requests:
      cpu: 200m
      memory: 1536Mi
    limits:
      cpu: 2
      memory: 2Gi

additionalCatalogs:
  ozone_iceberg: |-
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.data-query.svc.cluster.local:9083
    iceberg.file-format=PARQUET
    fs.native-s3.enabled=true
    s3.endpoint=http://ozone-s3g-rest.data-storage.svc.cluster.local:9878
    s3.region=us-east-1
    s3.path-style-access=true
    s3.aws-access-key=hadoop
    s3.aws-secret-key=ozone

ingress:
  enabled: true
  className: "traefik"
  hosts:
     - host: trinodb.localhost
       paths:
         - path: /
           pathType: ImplementationSpecific

  tls:
    - secretName: chart-example-tls
      hosts:
        - trinodb.localhost

additionalConfigProperties:
  - http-server.process-forwarded=true

# gateway:
#   enabled: true
#   parentRefs:
#     - name: trino-gateway
#       namespace: gateway-system
#       sectionName: https

#   hostnames:
#     - trinodb.localhost
#     - trinodb-prod.localhost

#   rules:
#     - path:
#         type: PathPrefix
#         value: /
#       filters:
#         - type: RequestHeaderModifier
#           requestHeaderModifier:
#             set:
#               - name: X-Forwarded-Proto
#                 value: https
