# storage/filestash.yaml
# Kubernetes manifest for Filestash Web UI pointing to Apache Ozone
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filestash
  namespace: data-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filestash
  template:
    metadata:
      labels:
        app: filestash
    spec:
      containers:
        - name: filestash
          image: machines/filestash:latest
          ports:
            - containerPort: 8334
          env:
            - name: S3_ENDPOINT
              value: "http://ozone-s3g:9878"
            - name: ADMIN_PASSWORD
              # BCRYPT HASH FOR admin
              value: "$2b$12$bHy0tCbZjCkjPCCodiMO0epdlOvoZie5qHBFZADoBXIRGVSXoXSfy"
---
apiVersion: v1
kind: Service
metadata:
  name: filestash
  namespace: data-storage
spec:
  selector:
    app: filestash
  ports:
    - port: 80
      targetPort: 8334
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filestash-ingress
  namespace: data-storage
spec:
  rules:
    - host: filestash.localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: filestash
                port:
                  number: 80
