# storage/ozone-values.yaml
# Helm configuration overides to deploy Apache Ozone locally

ozone:
  om:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
  scm:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  datanode:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
  s3g:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 768Mi
    # Important: exposed on port 9878 for the Data Platform
    service:
      type: ClusterIP
      port: 9878

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: ozone-recon.localhost
      paths:
        - path: /
          pathType: Prefix
