# bi/superset-values.yaml
# Helm overrides for Apache Superset

supersetNode:
  replicas: 1
supersetWorker:
  replicas: 1

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - superset.localhost

# Add Trino driver to the Superset image at runtime
bootstrapScript: |
  pip install sqlalchemy-trino
